version: '2'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    ports:
      - '8000:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - db
    volumes:
      - $PWD:/home
    expose:
      - "8000"
  db:
    image: postgres:11
    container_name: db
    hostname: db
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_test
  
networks:
  backend:
    driver: 'bridge'