"""1. First run

Revision ID: 58837ea5705e
Revises:
Create Date: 2022-08-13 17:19:06.360103

"""
# revision identifiers, used by Alembic.
revision = "58837ea5705e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
