"""1. First run

Revision ID: 6a75412ef116
Revises:
Create Date: 2022-08-13 16:59:47.649407

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6a75412ef116"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column(
            "course_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("course_id"),
        sa.UniqueConstraint("course_id"),
    )
    op.create_table(
        "students",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "course_sign_up",
        sa.Column(
            "course_sing_up_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.user_id"],
        ),
        sa.PrimaryKeyConstraint("course_sing_up_id"),
        sa.UniqueConstraint("course_sing_up_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_sign_up")
    op.drop_table("students")
    op.drop_table("courses")
    # ### end Alembic commands ###
