"""1. postgresql

Revision ID: dceff3de328a
Revises: 58837ea5705e
Create Date: 2022-08-14 12:17:03.035612

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "dceff3de328a"
down_revision = "58837ea5705e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column(
            "course_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("course_id"),
        sa.UniqueConstraint("course_id"),
    )
    op.create_table(
        "students",
        sa.Column(
            "student_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("student_id"),
        sa.UniqueConstraint("student_id"),
    )
    op.create_table(
        "course_sign_up",
        sa.Column(
            "course_sing_up_id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.course_id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.student_id"],
        ),
        sa.PrimaryKeyConstraint("course_sing_up_id"),
        sa.UniqueConstraint("course_sing_up_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_sign_up")
    op.drop_table("students")
    op.drop_table("courses")
    # ### end Alembic commands ###
