"""2. postgresql

Revision ID: ebb39c9ef0e2
Revises: dceff3de328a
Create Date: 2022-08-14 12:30:51.229990

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "ebb39c9ef0e2"
down_revision = "dceff3de328a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "course_sign_up", ["course_sing_up_id"])
    op.create_unique_constraint(None, "courses", ["course_id"])
    op.create_unique_constraint(None, "students", ["student_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "students", type_="unique")
    op.drop_constraint(None, "courses", type_="unique")
    op.drop_constraint(None, "course_sign_up", type_="unique")
    # ### end Alembic commands ###
